/**
 * 유저 직무 데이터
 */
export const Field = {
  DEVELOPMENT: 'DEVELOPMENT',
  MANAGEMENT: 'MANAGEMENT',
  MARKETING: 'MARKETING',
  ADVERTISING: 'ADVERTISING',
  DESIGN: 'DESIGN',
  SALES: 'SALES',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  RETAIL: 'RETAIL',
  GAME_PRODUCTION: 'GAME_PRODUCTION',
  MEDIA: 'MEDIA',
  HUMAN_RESOURCE: 'HUMAN_RESOURCE',
  ENGINEERING: 'ENGINEERING',
  FINANCE: 'FINANCE',
  MANUFACTURING: 'MANUFACTURING',
  MEDICAL: 'MEDICAL',
  BIO: 'BIO',
  LOGISTICS: 'LOGISTICS',
  TRADE: 'TRADE',
  EDUCATION: 'EDUCATION',
  LAW: 'LAW',
  CONSTRUCTION: 'CONSTRUCTION',
  PUBLIC_WELFARE: 'PUBLIC_WELFARE',
  NOT_SELECTED: 'NOT_SELECTED',
} as const;

/**
 * 유저 직무 데이터 타입
 */
export type Field = (typeof Field)[keyof typeof Field];
