import './globals.css';
import { PropsWithChildren } from 'react';
import TanstackQueryProvider from '@/providers/TanstackQueryProvider';
import ChakraUIProvider from '@/providers/ChakraProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <body>
        <TanstackQueryProvider>
          <ChakraUIProvider>{children}</ChakraUIProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
