
CHROMATIC_TOKEN=$(grep CHROMATIC_TOKEN .env | cut -d "=" -f2)
NEXT_PUBLIC_GOOGLE_CLIENT_ID=$(grep NEXT_PUBLIC_GOOGLE_CLIENT_ID .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_API_KEY=$(grep NEXT_PUBLIC_FIREBASE_API_KEY .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(grep NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(grep NEXT_PUBLIC_FIREBASE_PROJECT_ID .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(grep NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(grep NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_APP_ID=$(grep NEXT_PUBLIC_FIREBASE_APP_ID .env | cut -d "=" -f2)
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$(grep NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID .env | cut -d "=" -f2)
npx chromatic --project-token=$CHROMATIC_TOKEN